services:
  
  registry-server:
    image: registry-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: "starmap"
    hostname: "starmap"
    ports:
      - "${REGISTRY_SERVICE_PORT}:${REGISTRY_SERVICE_PORT}"
    env_file:
      .env
    depends_on:
      neo4j:
        condition: service_healthy
    networks: 
      - registry
      - starmap-net 

  neo4j:
    image: neo4j:latest
    container_name: neo4j-starmap
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
    ports:
      - "${NEO4J_PORT}:${NEO4J_PORT}"
      - "${NEO4J_UI_PORT}:${NEO4J_UI_PORT}"
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASS}", "RETURN 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks: 
      - registry

networks:
  registry:
    driver: bridge
  starmap-net:
    external: true
